logo: "layout/bolt.png"
bg: "layout/default_bg.jpg"
twitter: "https://www.twitter.com/JustSteveKing"
github: "https://www.github.com/JustSteveKing"
avatar: "layout/avatar.png"

twitter_handle: "@JustSteveKing"